- name: Install zsh
  homebrew:
      name: zsh
      state: present
  when: ansible_distribution == "MacOSX"

- name: Install zsh
  become: yes
  apt:
      name: zsh
      state: present
  when: ansible_distribution == "Ubuntu"

- name: Install zsh
  become: yes
  pkgng:
      name: zsh
      state: present
  when: ansible_distribution == "FreeBSD"
