- name: install binutils
  homebrew:
      name: binutils
      state: present
  when: ansible_distribution == "macosx"

- name: install binutils
  homebrew:
      name: binutils
      state: present
  when: ansible_os_family == "Debian"

- name: install binutils
  homebrew:
      name: binutils
      state: present
  when: ansible_distribution == "FreeBSD"
