- name: install binutils
  homebrew:
      name: binutils
      state: present
  when: ansible_distribution == "MacOSX"

- name: install binutils
  become: yes
  apt:
      name: binutils
      state: present
  when: ansible_os_family == "Debian"

- name: install binutils
  become: yes
  pkgng:
      name: binutils
      state: present
  when: ansible_distribution == "FreeBSD"
