- name: Install cscope code broswing tool
  homebrew:
      name: cscope
      state: present
  when: ansible_distribution == "MacOSX"

- name: Install cscope code broswing tool
  become: yes
  apt:
    name: cscope
    state: present
  when: ansible_os_family == "Debian"

- name: Install cscope code broswing tool
  become: yes
  pkgng:
    name: cscope
    state: present
  when: ansible_distribution == "FreeBSD"
