- name: install coreutils
  homebrew:
      name: coreutils
      state: present
  when: ansible_distribution == "macosx"

- name: install coreutils
  homebrew:
      name: coreutils
      state: present
  when: ansible_os_family == "Debian"

- name: install coreutils
  homebrew:
      name: coreutils
      state: present
  when: ansible_distribution == "FreeBSD"
