- name: Install neovim
  homebrew:
      name: neovim/neovim/neovim
      state: present
  when: ansible_distribution == "MacOSX"

- name: Add neovim PPA
  become: yes
  apt_repository:
      repo: "ppa:neovim-ppa/unstable"
      update_cache: yes
  when: ansible_distribution == "Ubuntu"

#TODO: Add Debian-specific magic here

- name: Install neovim
  become: yes
  apt:
      name: neovim
      state: present
  when: ansible_os_family == "Debian"

- name: Install neovim
  become: yes
  pkgng:
      name: neovim
      state: present
  when: ansible_distribution == "FreeBSD"
