- name: Ensure that the desired git repository folder exists
  file:
      state: directory
      path: "{{ git_repo_folder }}"

- name: Check if personal zsh configuration repository exists locally
  stat:
      path: "{{ git_repo_folder }}/config.zsh"
  register: st

- name: Acquire personal zsh configuration
  git:
      repo: https://github.com/cmrosenberg/config.zsh.git
      dest: "{{ git_repo_folder }}/config.zsh"
  when: st.stat.isdir is not defined

- name: Link core configuration to ~/.zshrc
  file:
      state: link
      src: "{{ git_repo_folder }}/config.zsh/zshrc"
      dest: ~/.zshrc
