- name: Install git
  homebrew:
      name: git
      state: present
  when: ansible_distribution == "MacOSX"

- name: Install git
  become: yes
  apt:
      name: git
      state: present
  when: ansible_os_family == "Debian"

- name: Install git
  become: yes
  pkgng:
      name: git
      state: present
  when: ansible_distribution == "FreeBSD"
