- name: Install par paragraph formatter
  homebrew:
      name: par
      state: present
  when: ansible_distribution == "MacOSX"

- name: Install par paragraph formatter
  become: yes
  apt:
    name: par
    state: present
  when: ansible_os_family == "Debian"

- name: Install par paragraph formatter
  become: yes
  pkgng:
    name: par_format
    state: present
  when: ansible_distribution == "FreeBSD"
