- name: Install emacs
  homebrew:
      name: emacs
      install_options: with-cocoa
  when: ansible_distribution == "MacOSX"

- name: Install emacs
  become: yes
  apt:
      name: emacs
      state: present
  when: ansible_distribution == "Ubuntu"
