- name: Install tig (git utility)
  homebrew:
      name: tig
      state: present
  when: ansible_distribution == "MacOSX"

- name: Install tig (git utility)
  become: yes
  apt:
      name: tig
      state: present
  when: ansible_os_family == "Debian"

- name: Install tig (git utility)
  become: yes
  pkgng:
      name: tig
      state: present
  when: ansible_distribution == "FreeBSD"
