- name: Install tree
  homebrew:
      name: tree
      state: present
  when: ansible_distribution == "MacOSX"

- name: Install tree
  become: yes
  apt:
      name: tree
      state: present
  when: ansible_os_family == "Debian"

- name: Install tree
  become: yes
  pkgng:
      name: tree
      state: present
  when: ansible_distribution == "FreeBSD"
