- name: install findutils
  homebrew:
      name: findutils
      state: present
  when: ansible_distribution == "macosx"

- name: install findutils
  homebrew:
      name: findutils
      state: present
  when: ansible_os_family == "Debian"

- name: install findutils
  homebrew:
      name: findutils
      state: present
  when: ansible_distribution == "FreeBSD"
