- name: Install tmux and reattach-to-user-namespace
  homebrew:
    pkg: "{{ item }}"
    state: present
  with_items:
      - tmux
      - reattach-to-user-namespace
  when: ansible_distribution == "MacOSX"

- name: Install tmux and xclip
  become: yes
  apt:
    name: "{{ item }}"
    state: present
  with_items:
      - tmux
      - xclip
  when: ansible_distribution == "Ubuntu"

- name: Install tmux and xclip
  become: yes
  pkgng:
    name: "{{ item }}"
    state: present
  with_items:
      - tmux
      - xclip
  when: ansible_distribution == "FreeBSD"
